---
- name: Afficher le contenu d'un fichier CSV
  hosts: localhost
  vars:
    temps: "{{ ansible_date_time.date }}T{{ ansible_date_time.hour }}:00"
  tasks:

    - name : Appeler API open-meteo et récupérer du JSON
      uri:
        url: >
             https://api.open-meteo.com/v1/forecast?latitude=43.6191717&longitude=6.9471323&
             current=temperature_2m,wind_speed_10m&hourly=temperature_2m,relative_humidity_2m,wind_speed_10m
        method: GET
        return_content: yes
      register: api_response

    - name: Parser et afficher le current time et la temperature
      debug:
        msg:
          - > 
            "Current Time {{ api_response.json.current.time | regex_replace(':.*$', ':00') }} 
            and temperature {{ api_response.json.current.temperature_2m}}"

    # Read a CSV file and access the first item
    - name: Read temperatures from CSV file and return a list
      community.general.read_csv:
        path: temperature.csv
      register: temperatures
#      delegate_to: localhost

    - name: Parcours dict temperature
      ansible.builtin.debug:
        msg: "Date {{ item.time }} et temperature {{ item.temperature }}"
      loop: "{{ temperatures }}"
