---
- name: Afficher le contenu d'un fichier CSV
  hosts: localhost
  vars:
    temps: "{{ ansible_date_time.date }}T{{ ansible_date_time.hour }}:00"
  tasks:
    - name: Lire un fichier CSV
      debug:
        msg: 
          - "Le temps = {{ temps }}"
          - "{{ lookup('csvfile', '{{ temps }}', delimiter=',', file='temperature.csv') }}"
