---
- name: Afficher le contenu d'un fichier CSV
  hosts: localhost
  tasks:
    - name: Lire un fichier CSV
      debug:
        msg: 
          - "Test"
          - "{{ lookup('csvfile', '2025-02-12T23:00', delimiter=',', file='temperature.csv') }}"
