---
- name: Afficher le contenu d'un fichier CSV
  hosts: localhost
  vars:
    temps: "{{ ansible_date_time.date }}T{{ ansible_date_time.hour }}:00"
    utilisateurs:
      - name: "Alice"
        age: 30
      - name: "Bob"
        age: 16
      - name: "Charlie"
        age: 22

  tasks:

    - name: Appeler API open-meteo et récupérer du JSON
      ansible.builtin.uri:
        url: "https://api.open-meteo.com/v1/forecast?latitude=43.6191717&longitude=6.9471323&\
             current=temperature_2m,wind_speed_10m&hourly=temperature_2m,relative_humidity_2m,wind_speed_10m"
        method: GET
        return_content: true
      register: api_response

    - name: Parser et afficher le current time et la temperature
      ansible.builtin.debug:
        msg:
          - >
            "Current Time {{ api_response.json.current.time | regex_replace(':.*$', ':00') }}
            and temperature {{ api_response.json.current.temperature_2m}}"

    # Read a CSV file and access the first item
    - name: Read temperatures from CSV file and return a list
      community.general.read_csv:
        path: temperature.csv
      register: temperatures
#      delegate_to: localhost

    - name: Afficher uniquement les utilisateurs majeurs
      debug:
        msg: "{{ item.name }} est majeur(e), âge : {{ item.age }}"
      loop: "{{ utilisateurs }}"
      when: item.age + 2 >= 16

    - name: Parcours dict temperature
      ansible.builtin.debug:
        msg: "Date {{ item.time }} et temperature {{ (item.temperature+5) }} supérieure à {{ api_response.json.current.temperature_2m }}"
      loop: "{{ temperatures.list }}"
      when: item.temperature | int + 5 > api_response.json.current.temperature_2m | int
      
    - name: Filter personnalisé
      debug:
        msg: "{{ 'ansible' | reverse_string }}"