---
- name: Test jour heure
  hosts: all
  become: true
  become_user: root
  vars:
    monJour: "{{ ansible_date_time.day }}"
    monHeure: "{{ ansible_date_time.hour }}"

  tasks:
    - name: Jour et Heure dans /etc/jour
      ansible.builtin.template:
        src: template/jour.j2
        dest: /etc/jour

