---
- name: Installer paquets requis
  ansible.builtin.apt:
    name:
      - mysql-server
    state: present
    update_cache: yes

- name: Démarrer et activer MySQL
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes

- name: Sécuriser MySQL root (optionnel, à adapter)
  community.mysql.mysql_user:
    login_user: root
    login_password: 'ambient'
    user: root
    password: "{{ db_root_password }}"
    host_all: yes
    check_implicit_admin: yes
  ignore_errors: yes

- name: Créer base de données WordPress
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: present

- name: Créer utilisateur MySQL pour WordPress
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    host: localhost
    state: present
