---
- name: Afficher le contenu d'un fichier CSV
  hosts: all
  vars:
    temps: "{{ ansible_date_time.date }}T{{ ansible_date_time.hour }}:00"
    utilisateurs:
      - name: "Alice"
        age: 30
      - name: "Bob"
        age: 16
      - name: "Charlie"
        age: 22

  tasks:

    - name: Afficher uniquement les utilisateurs majeurs
      ansible.builtin.debug:
        msg: "{{ item.name }} est majeur(e), âge : {{ item.age }}"
      loop: "{{ utilisateurs }}"
      when: item.age >= 18
