---
- name: Installer apache2 et mysql-server
  hosts: all
  become: yes
  tasks:
    - name: Installer apache2
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apache2
        - mysql-server
      register: package_check

    - name: Remplacer le titre de la page HTML
      ansible.builtin.replace:
        path: /var/www/html/index.html
        regexp: 'Apache2 Default Page'
        replace: 'Apache2 Default Page from Ansible'