---
- name: Installer et configurer docker
  hosts: all
  remote_user: root
  become: true
  become_user: root

  vars:
    docker_users:
      - vagrant

  roles:
    - geerlingguy.docker
    - geerlingguy.clamav