---
- name : Import playbook tp3
  ansible.builtin.import_playbook: tp3.yml
#- name : Import playbook tp4
#  ansible.builtin.import_playbook: tp4.yml

- name: Écrire la date et l'heure dans /etc/last_changed
  hosts: all
  become: yes
  tasks:
    - name: Récupérer la date et l'heure actuelles
      set_fact:
        current_datetime: "{{ lookup('pipe', 'date +\"%Y-%m-%d %H:%M:%S\"') }}"

    - name: Écrire la date et l'heure dans /etc/last_changed
      lineinfile:
        path: /etc/last_changed
        line: "Dernière modification : {{ current_datetime }}"
        insertafter: EOF