---
- name: Installer apache2
  hosts: web
  become: true
  become_user: root
  roles:
    - wordpress
  
- name: Installer mysql-server
  hosts: db
  become: true
  become_user: root

  tasks:
    - name: Install mysql-server
      ansible.builtin.apt:
        update_cache: true
        name: "{{ item }}"
        state: present
      loop:
        - mysql-server
